### ISSUE TITLE
Copy existing Wagtail utility, helper, or supporting code into this library

### ISSUE THREAD

**Issue by jmurty** [ixc/wagtail-extensions#1]
From @aweakley's comment https://github.com/ixc/agsa/issues/190#issuecomment-377140773

Look at Mark's recent commits and see what could be extracted into a generic repo - I'm pretty sure he's done a few generic wagtail fixes?

Also this commit from Biennale could be part of it (Mark wrote it, I copied it...): ixc/biennale-of-sydney@39ac903 - but note that we had trouble with the call to static() in wagtail_hooks, and ended up with this:
https://github.com/ixc/biennale-of-sydney/blob/2954ecdb6d71433a5e875feb80f13d32028553f0/biennale_work_creator/wagtail_hooks.py#L18

**Comment by markfinger** [comment]
I've been musing over this ticket for a while, but I don't think that there's much worth copying out just yet. 

Probably the only useful thing is the field placeholder/proxy thing that fetches default data from jsonfields to populate normal db fields: https://github.com/ixc/agsa/blob/8cbc3789bbc4c321ad6bbd0a321489c0324283e7/agsa/collection/models.py#L34-L135

But even that still needs to be kicked around for a bit and actually used in a production environment before it's wise to abstract it.

**Comment by markfinger** [comment]
I think we should probably wait until we've finished AGSA (and maybe AusMus) before we start teasing out commonalities.
